export const browserCoreExamples = [
  "assistme browser status",
  "assistme browser start",
  "assistme browser stop",
  "assistme browser tabs",
  "assistme browser open https://example.com",
  "assistme browser focus abcd1234",
  "assistme browser close abcd1234",
  "assistme browser screenshot",
  "assistme browser screenshot --full-page",
  "assistme browser screenshot --ref 12",
  "assistme browser snapshot",
  "assistme browser snapshot --format aria --limit 200",
  "assistme browser snapshot --efficient",
  "assistme browser snapshot --labels",
];

export const browserActionExamples = [
  "assistme browser navigate https://example.com",
  "assistme browser resize 1280 720",
  "assistme browser click 12 --double",
  'assistme browser type 23 "hello" --submit',
  "assistme browser press Enter",
  "assistme browser hover 44",
  "assistme browser drag 10 11",
  "assistme browser select 9 OptionA OptionB",
  "assistme browser upload /tmp/assistme/uploads/file.pdf",
  'assistme browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "assistme browser dialog --accept",
  'assistme browser wait --text "Done"',
  "assistme browser evaluate --fn '(el) => el.textContent' --ref 7",
  "assistme browser console --level error",
  "assistme browser pdf",
];
